# Generated by Django 3.0.3 on 2020-09-07 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_listings_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='image_url',
            field=models.URLField(default='https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png'),
        ),
    ]
