# Generated by Django 3.0.3 on 2020-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200907_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='current_bid',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='my_items',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Auction_Listings'),
        ),
    ]
